def configure(conf):
    pass

def build(bld):
    Box2D = bld.new_task_gen(features = 'cxx cstaticlib',
                                   includes = '.',
                                   target = 'Box2D')
    Box2D.find_sources_in_dirs('. ./../collision ./../common ./../dynamics ./../rope')
