name: CI - Editor Only

on:
  push:
    branches:
      - 'DEFEDIT-*'
      - 'editor-dev'
  pull_request:
    branches:
      - 'DEFEDIT-*'
      - 'editor-dev'

env:
  S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
  S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
  NOTARIZATION_USERNAME: ${{ secrets.NOTARIZATION_USERNAME }}
  NOTARIZATION_PASSWORD: ${{ secrets.NOTARIZATION_PASSWORD }}
  NOTARIZATION_ITC_PROVIDER: ${{ secrets.NOTARIZATION_ITC_PROVIDER }}
  DM_PACKAGES_URL: ${{ secrets.DM_PACKAGES_URL }}
  MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
  MACOS_CERTIFICATE_PASS: ${{ secrets.MACOS_CERTIFICATE_PASS }}
  DEFOLD_EDITOR_DISABLE_PERFORMANCE_TESTS: true


jobs:
  build-and-notarize-editor:
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: macOS-latest
    steps: [
      { name: 'Checkout', uses: actions/checkout@v2 },
      { name: 'Fetch tags', run: 'git fetch --depth=1 origin +refs/tags/*:refs/tags/*' },
      { name: 'Install Python', uses: actions/setup-python@v1, with: { python-version: 2.x, architecture: x64 } },
      { name: 'Install Java', uses: actions/setup-java@v1, with: { java-version: '11.0.2' } },
      { name: 'Install Leiningen', uses: DeLaGuardo/setup-clojure@master, with: { lein: 2.8.3 } },
      {
        name: 'Install dependencies',
        run: 'ci/ci.sh --keychain-cert="${{env.MACOS_CERTIFICATE}}" --keychain-cert-pass="${{env.MACOS_CERTIFICATE_PASS}}" install'
      },
      {
        name: 'Build editor',
        run: 'ci/ci.sh build-editor'
      },
      {
        name: 'Notarize editor',
        run: 'ci/ci.sh --notarization-username="${{env.NOTARIZATION_USERNAME}}" --notarization-password="${{env.NOTARIZATION_PASSWORD}}" --notarization-itc-provider="${{env.NOTARIZATION_ITC_PROVIDER}}" notarize-editor'
      },
      {
        name: 'Archive editor',
        run: 'ci/ci.sh archive-editor'
      },
      {
        name: 'Release editor',
        run: 'ci/ci.sh release'
      }]
